version: '3'

services:
  service1:
    container_name: service1
    image: 'kurtis/service1:v1'
    ports:
      - 8081:8080
    environment:
      SERVICE2_ADDRESS: 'http://service2:8080/'

  service2:
    container_name: service2
    image: 'kurtis/service2:v1'
    ports:
      - 8082:8080
    environment:
      SERVICE3_ADDRESS: 'http://service3:8080/'
      SERVICE4_ADDRESS: 'http://service4:8080/'

  service3:
    container_name: service3
    image: 'kurtis/service3:v1'
    ports:
      - 8083:8080
    environment:
      SERVICE4_ADDRESS: 'http://service4:8080/'

  service4:
    container_name: service4
    image: 'kurtis/service4:v1'
    ports:
      - 8084:8080

  zipkin:
    container_name: zipkin
    image: 'openzipkin/zipkin:2.10'
    ports:
      - 9411:9411
    environment:
      STORAGE_TYPE: 'mysql'
      MYSQL_HOST: 'db'
    depends_on:
      - db

  db:
    container_name: db
    image: 'openzipkin/zipkin-mysql:2.10'

volumes:
  zipkin-db:
    driver: local