apiVersion: v1
kind: Service
metadata:
  labels:
    app: kiali
  name: kiali-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: kiali-http
    port: 80
    protocol: TCP
    targetPort: 20001
  selector:
    app: kiali
  sessionAffinity: None
  type: LoadBalancer