apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: kibana-http
    port: 80
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
  sessionAffinity: None
  type: LoadBalancer