apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: prometheus-http
    port: 80
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: None
  type: LoadBalancer