apiVersion: v1
kind: Service
metadata:
  labels:
    app: servicegraph
  name: servicegraph-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: servicegraph-http
    port: 80
    protocol: TCP
    targetPort: 8088
  selector:
    app: servicegraph
  sessionAffinity: None
  type: LoadBalancer