apiVersion: v1
kind: Service
metadata:
  labels:
    app: zipkin
  name: grafana-lb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: grafana-http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer