spring:
  application:
    name: @project.name@
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 1.0
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health, metrics'
  metrics:
    enable:
      system: true